version: '3'
services:
  ex_double_entry:
    build: .
    environment:
      POSTGRES_DB: ex_double_entry_test
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ex_double_entry_test
