version: '3'
services:
  ex_double_entry:
    build: .
    environment:
      POSTGRES_DB_NAME: ex_double_entry_test
      POSTGRES_DB_HOST: postgres
    volumes:
      - ./:/ex_double_entry/
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ex_double_entry_test
